apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bjseefsm1-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.xjiang0903b.tmkt.p3.openshiftapps.com/rhtap/rhtap-qe:e12e37fe818fef287cde5332fc7e0a3f6958706e@sha256:7f72f0c27c75f894c7ca2f929eb3e914aa6694dd71e5294d7c2d79d5399d77ac
          name: container-image
